### PR TITLE
Change reference to Omnimatter in startup message and fix compression icon size issue

### LINKED ISSUE #199: [BUG][omnicompression]Icons with inherited size are set to 32px and 0 mipmaps
**Describe the bug**
Any icon that is set in IconData but has icon_size or mipmaps assigned by the parent IconSpecification will have those properties removed and replaced with the default of 32px and 0 mipmaps.

An example table where this would happen is below
```lua
{
    name = "an-item",
    icons = {
        {
            icon = "not_a_path.png"
        }
    },
    icon_size = 64,
    mipmaps = 4
}
```
**To Reproduce**
Omnicompression plus reskins-bobs, look at most any compressed icon in the crafting menu.

**Expected behavior**
Icons would look normal with the respective omnicompression overlays.

**Screenshots**
image
image

**Additional context**
I've put in a PR at #198 for review, but my Github skills are lacking so it merged two different changes I had wanted to make.

**Additional Info**
- Factorio Version: 0.18.32
- Minimal required mods to reproduce:
bobpower 0.18.6/boblibrary 0.18.9
reskins-bobs 0.0.9/reskins-library 0.0.5
omnimatter_compression  #3.18.7/omnilib 3.18.13

### PR DESCRIPTION
**Pull request by oorzkws**
Omnimatter -> Omnimods, since most mods that use omnilib can run without omnimatter.

Fixes #199

### CODE REVIEW

**Comment by oorzkws** [comment]
I'm not very good at github, the other changes I made ended up merged in here.

File: omnimatter_compression/function.lua [hunk 1]
```diff
@@ -60,61 +60,48 @@ end
...
+      for i, icon in pairs(icons) do-- Apply inherited attributes as explicit for each layer
+        icon.icon_size = icon.icon_size or raw_item.icon_size
+        icon.icon_mipmaps = icon.icon_mipmaps or raw_item.icon_mipmaps
       end
+      return icons
+    elseif raw_item.icon then
+      return {{
+        icon = raw_item.icon,
+        icon_size = raw_item.icon_size
+      }}
```
Comment (SqFKYo) [inline omnimatter_compression/function.lua:93]: Shouldn't this also check for icon_mipmaps?

File: omnimatter_compression/function.lua [hunk 2]
```diff
@@ -60,61 +60,48 @@ end
...
+      local icons = table.deepcopy(raw_item.icons)
+      for i, icon in pairs(icons) do-- Apply inherited attributes as explicit for each layer
+        icon.icon_size = icon.icon_size or raw_item.icon_size
+        icon.icon_mipmaps = icon.icon_mipmaps or raw_item.icon_mipmaps
       end
+      return icons
+    elseif raw_item.icon then
+      return {{
+        icon = raw_item.icon,
+        icon_size = raw_item.icon_size
```
Comment (SqFKYo) [inline omnimatter_compression/function.lua:92]: Shouldn't this also check for icon_mipmaps?

Comment (oorzkws) [reply omnimatter_compression/function.lua:92]: According to IconSpecification if it's _icon_ not _icons_, it doesn't support the mipmap attribute.

Comment (kirazy) [reply omnimatter_compression/function.lua:92]: I don't think that's true. That's possibly an error with the wiki, a lot of vanilla icons (all of them?) have icon_mipmaps specified and they use almost exclusively icon.

Comment (oorzkws) [reply omnimatter_compression/function.lua]: Fixed in c640e00

File: omnimatter_compression/function.lua [hunk 3]
```diff
@@ -89,7 +89,8 @@ local function find_result_icon(raw_item)
     elseif raw_item.icon then
       return {{
         icon = raw_item.icon,
-        icon_size = raw_item.icon_size
+        icon_size = raw_item.icon_size,
+        icon_mipmaps = raw_item.icon_mipmaps
```
Comment (SqFKYo) [inline omnimatter_compression/function.lua:93]: You'll want to add a check if mipmaps exist since this will probably crash on items that define icon, but don't use mipmaps.

Comment (kirazy) [reply omnimatter_compression/function.lua:93]: Is that necessary? The code only gets this far if there is not an `icons` field, so we're just dealing with a standard flat icon at this point. Mipmaps is an optional field, and so the code as written just means that `icon_mipmaps` would be nil, since in this hypothetical, `raw_item.icon_mipmaps = nil`, so the return would be `icon` and `icon_size`. 

The game treats a nil `icon_mipmaps` field as 1. I don't think not checking for the existence of raw_item.icon_mipmaps would case a startup error.

Comment (oorzkws) [reply omnimatter_compression/function.lua:93]: Since the raw_item.icon_mipmaps is a number, not a table, we don't risk trying to index a nil table. If it *is* nil, the game simply applies default behavior as if it hadn't been defined in the prototype (the correct outcome). Additionally, since this is the condition for `icon`, not `icons`, we don't risk setting a value that already exists to nil.

Comment (SqFKYo) [reply omnimatter_compression/function.lua:93]: Thanks for the clarification. I had no idea about this usage, as mostly the game seems to crash when you fail to remember a check somewhere. Looking good then :)

**Comment by Samuel2507** [comment]
Thanks for contributing!
